/* testing the procedures comment/uncomment to test individual bits */

/*
--TEST GET LOCATION BY ID
GO
BEGIN
	DECLARE @LCUR CURSOR;
	EXEC GET_LOCATION_BY_ID @PLOCID = 'MLB3931', @POUTCUR = @LCUR OUTPUT;

	DECLARE @LOCID NVARCHAR(8),
		@LOCNAME NVARCHAR(100),
		@ADDRESS NVARCHAR(100),
		@MANAGER NVARCHAR(100);

	FETCH NEXT FROM @LCUR INTO @LOCID, @LOCNAME, @ADDRESS, @MANAGER;

	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT(CONCAT('LOCATION ID: ', @LOCID, ' LOCATION NAME: ', @LOCNAME, ' ADDRESS: ', @ADDRESS, ' MANAGER: ', @MANAGER))
		FETCH NEXT FROM @LCUR INTO @LOCID, @LOCNAME, @ADDRESS, @MANAGER;
	END;

	CLOSE @LCUR;
	DEALLOCATE @LCUR;

END
*/

--TEST ADD LOCATION
GO
BEGIN
SELECT * FROM LOCATION3815
SELECT * FROM INVENTORY3815
EXEC ADD_LOCATION @PLOCID = 'GIZ1324', @PLOCNAME = 'Gizland', @PLOCADDRESS = '123 fake st', @PMANAGER = 'Bob Dole'
--EXEC ADD_LOCATION @PLOCID = 'TURBO666', @PLOCNAME = 'TURBOLAND', @PLOCADDRESS = '420 EXTREME Way', @PMANAGER = 'Tony Hawk'
SELECT * FROM LOCATION3815
SELECT * FROM INVENTORY3815

END;

--TEST ADD PRODUCT
GO
BEGIN
DECLARE @PRODID INT 
SELECT * FROM INVENTORY3815
EXEC @PRODID = ADD_PRODUCT @PPRODNAME = 'RAM', @PBUYPRICE = 5, @PSELLPRICE = 25;
PRINT @PRODID
--EXEC ADD_PRODUCT @PPRODNAME = 'CPU', @PBUYPRICE = 20, @PSELLPRICE = 50;
SELECT * FROM INVENTORY3815
END;

--TEST ADD CLIENT ACCOUNT
GO
BEGIN
	DECLARE @CLIENTID INT
	EXEC @CLIENTID = ADD_CLIENT_ACCOUNT @PACCTNAME = 'TEST ACCT', @PBALANCE = '2000', @PCREDITLIMIT = 20000.00
	PRINT @CLIENTID
	SELECT * FROM CLIENTACCOUNT3815
END;


--TEST ADD AUTHORISED PERSON
GO
BEGIN
	DECLARE @AUTHID INT
	EXEC @AUTHID = ADD_AUTHORISED_PERSON @PFIRSTNAME = 'TEST', @PSURNAME = 'MAN', @PEMAIL = 'TESTMAN@TESTMAN.COM', @PPASSWORD = 'BOLONGA22', @PACCOUNTID = 30002
	PRINT @AUTHID
END;


--TEST GET PRODUCT BY ID
GO
BEGIN
	DECLARE @PCUR CURSOR;
	EXEC GET_PRODUCT_BY_ID @PPRODID = 10001, @POUTCUR = @PCUR OUTPUT;

	DECLARE @PRODID INT,
		@PRODNAME NVARCHAR(100),
		@BUYPRICE MONEY,
		@SELLPRICE MONEY;

	FETCH NEXT FROM @PCUR INTO @PRODID, @PRODNAME, @BUYPRICE, @SELLPRICE;

	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT(CONCAT('PRODUCT ID: ', @PRODID, ' PRODUCT NAME: ', @PRODNAME, ' BUYPRICE: ', @BUYPRICE, ' SELLPRICE: ', @SELLPRICE))
		FETCH NEXT FROM @PCUR INTO @PRODID, @PRODNAME, @BUYPRICE, @SELLPRICE; 
	END;

	CLOSE @PCUR;
	DEALLOCATE @PCUR;

END

--TEST GET CLIENT BY ID
GO
BEGIN
	DECLARE @CCUR CURSOR;
	EXEC GET_CLIENT_ACCOUNT_BY_ID @PACCOUNTID = 30001, @POUTCUR = @CCUR OUTPUT;

	DECLARE @CLIENTID INT,
		@ACCTNAME NVARCHAR(100),
		@BALANCE MONEY,
		@CREDITLIMIT MONEY,
		@USERID INT,
		@FIRSTNAME NVARCHAR(100),
		@SURNAME NVARCHAR(100),
		@EMAIL NVARCHAR(100),
		@PASSWORD NVARCHAR(100),
		@ACCOUNTID INT;

	FETCH NEXT FROM @CCUR INTO @CLIENTID, @ACCTNAME, @BALANCE, @CREDITLIMIT, @USERID, @FIRSTNAME, @SURNAME, @EMAIL, @PASSWORD, @ACCOUNTID;

	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT(CONCAT('CLIENT ID: ', @CLIENTID, ' ACCOUNT NAME: ', @ACCTNAME, ' BALANCE: ', @BALANCE,
		' CREDIT LIMIT: ', @CREDITLIMIT, ' USER ID: ', @USERID, ' FIRSTNAME ', @FIRSTNAME,
		' SURNAME: ', @SURNAME, ' EMAIL: ', @EMAIL, ' PASSWORD: ', @PASSWORD, ' AUTHED CLIENT ID: ', @ACCOUNTID));
		FETCH NEXT FROM @CCUR INTO @CLIENTID, @ACCTNAME, @BALANCE, @CREDITLIMIT, @USERID, @FIRSTNAME, @SURNAME, @EMAIL, @PASSWORD, @ACCOUNTID; 
	END;

	CLOSE @CCUR;
	DEALLOCATE @CCUR;

END
GO


--TEST PURCHASE STOCK
GO
BEGIN
	SELECT * FROM GENERALLEDGER3815
	SELECT * FROM INVENTORY3815
	EXEC PURCHASE_STOCK @PPRODID = 10001, @PLOCID = 'MLB3931', @PQTY =5;
	SELECT * FROM GENERALLEDGER3815
	SELECT  * FROM INVENTORY3815

END;


--TEST CREATE ORDER
GO
BEGIN
SELECT * FROM ORDER3815
EXEC CREATE_ORDER @PSHIPPINGADDRESS = '123 Fake St', @PUSERID = 50002
SELECT * FROM ORDER3815
END;

--TEST GET_ORDER_BY_ID
GO
BEGIN
	DECLARE @OCUR CURSOR;
	EXEC GET_ORDER_BY_ID @PORDERID = 70001, @POUTCUR = @OCUR OUTPUT;

	DECLARE @ORDERID INT,
		@SHIPPINGADDRESS NVARCHAR(100),
		@DATETIMECREATED DATETIME,
		@DATETIMEDISPATCHED DATETIME,
		@TOTAL MONEY,
		@USERID INT,
		@ORDERLID INT,
		@PRODUCTID INT,
		@QTY INT,
		@DISCOUNT DECIMAL,
		@SUBTOTAL MONEY;

	FETCH NEXT FROM @OCUR INTO @ORDERID, @SHIPPINGADDRESS, @DATETIMECREATED, @DATETIMEDISPATCHED, @TOTAL,
	@USERID, @ORDERLID, @PRODUCTID, @QTY, @DISCOUNT, @SUBTOTAL;

	WHILE @@FETCH_STATUS = 0
	BEGIN
	--second orderid not printed
		PRINT(CONCAT('ORDER ID: ', @ORDERID, ' SHIPPING ADDRESS: ', @SHIPPINGADDRESS,
		' DATETIME CREATED: ', @DATETIMECREATED, ' DATETIME DISPATCHED: ', @DATETIMEDISPATCHED,
		' TOTAL: $', @TOTAL, 'USER ID: ', @USERID, ' PRODUCTID: ', @PRODUCTID, ' QUANTITY: ', @QTY, ' DISCOUNT: ', @DISCOUNT, ' SUBTOTAL: $', @SUBTOTAL))
		FETCH NEXT FROM @OCUR INTO @ORDERID, @SHIPPINGADDRESS, @DATETIMECREATED, @DATETIMEDISPATCHED, @TOTAL,
		@USERID, @ORDERLID, @PRODUCTID, @QTY, @DISCOUNT, @SUBTOTAL;
	END;

	CLOSE @OCUR;
	DEALLOCATE @OCUR;
END;



--TEST MAKE ACCOUNT PAYMENT
GO
BEGIN
	SELECT * FROM GENERALLEDGER3815;
	SELECT BALANCE FROM CLIENTACCOUNT3815 WHERE ACCOUNTID = 30001;
	EXEC MAKE_ACCOUNT_PAYMENT @PACCOUNTID = 30001, @PAMOUNT = 50;
	SELECT BALANCE FROM CLIENTACCOUNT3815 WHERE ACCOUNTID = 30001;
	SELECT * FROM GENERALLEDGER3815;
	SELECT * FROM ACCOUNTPAYMENT3815;
END;


--TEST GET OPEN ORDERS
GO
BEGIN
	DECLARE @OCUR CURSOR;
	EXEC GET_OPEN_ORDERS @POUTCUR = @OCUR OUTPUT;

	DECLARE @ORDERID INT,
		@SHIPPINGADDRESS NVARCHAR(100),
		@DATETIMECREATED DATETIME,
		@DATETIMEDISPATCHED DATETIME,
		@TOTAL MONEY,
		@USERID INT;

	FETCH NEXT FROM @OCUR INTO @ORDERID, @SHIPPINGADDRESS, @DATETIMECREATED, @DATETIMEDISPATCHED, @TOTAL, @USERID;

	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT(CONCAT('ORDER ID: ', @ORDERID, ' SHIPPING ADDRESS: ', @SHIPPINGADDRESS,
		' DATETIME CREATED: ', @DATETIMECREATED, ' DATETIME DISPATCHED: ', @DATETIMEDISPATCHED,
		' TOTAL: $', @TOTAL, 'USER ID: ', @USERID))
		FETCH NEXT FROM @OCUR INTO @ORDERID, @SHIPPINGADDRESS, @DATETIMECREATED, @DATETIMEDISPATCHED, @TOTAL, @USERID;
	END;

	CLOSE @OCUR;
	DEALLOCATE @OCUR;
END;



--TEST ADD PRODUCT TO ORDER
GO
BEGIN
	--ORDER FULFILLED
	--EXEC ADD_PRODUCT_TO_ORDER @PORDERID = 70001, @PPRODID = 10001, @PQTY = 5, @DISCOUNT = 0;
	EXEC ADD_PRODUCT_TO_ORDER @PORDERID = 70002, @PPRODID = 10001, @PQTY = 1, @DISCOUNT = 0.1;
	SELECT * FROM ORDER3815
	SELECT * FROM ORDERLINE3815
	--EXEC ADD_PRODUCT_TO_ORDER @PORDERID = 70002, @PPRODID = 10001, @PQTY = 1, @DISCOUNT = 0.1;
	EXEC ADD_PRODUCT_TO_ORDER @PORDERID = 70002, @PPRODID = 10002, @PQTY = 5, @DISCOUNT = 0.1;
	SELECT * FROM ORDER3815
	SELECT * FROM ORDERLINE3815


END;

--TEST REMOVE PRODUCT FROM ORDER
GO
BEGIN
EXEC REMOVE_PRODUCT_FROM_ORDER @PORDERID = 70002, @PPRODID = 10002;
SELECT * FROM ORDER3815 WHERE ORDERID = 70002
END;

--TEST FULFIL ORDER
GO
BEGIN
SELECT * FROM CLIENTACCOUNT3815
SELECT * FROM GENERALLEDGER3815
SELECT * FROM ORDER3815
EXEC FULLFILL_ORDER @PORDERID = 70002

SELECT * FROM GENERALLEDGER3815
END;